# Generated by Django 4.2.3 on 2023-07-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='location',
            new_name='lastname',
        ),
    ]
